### ISSUE TITLE
simplify processing

### ISSUE THREAD

**Issue by pkra** [heytitle/latex-sketch-plugin#1]
MathJax team member here. I just stumbled up on this thanks to a pointer from a developer.

You can simplify `returnSVG` by configuring MathJax's SVG output, cf. http://docs.mathjax.org/en/latest/options/output-processors/SVG.html

* `useGlobalCache: false` will add the paths to the SVG for re-sue. If `use` elements are a problem more generally, set `useFontCache:false` .
* `blacker: 0` will set the stroke-width to `0` (or of course any other value you like) so you don't have rewrite that.

I would probably drop the Preview output processor (which only runs on the first expression anyway but adds jitter).

**Comment by heytitle** [comment]
Hi @pkra ,

Sry for late reply and thanks for the feedback.

**Comment by heytitle** [comment]
Fixed in : https://github.com/heytitle/latex-sketch-plugin/commit/d254ec5dfd821cb3c3125e6d10168d15fcb42870

@pkra thanks for reporting!
