### ISSUE TITLE
improve the readme or make the plugin more easily accessible 

### ISSUE THREAD

**Issue by JCLaHoot** [heytitle/latex-sketch-plugin#2]
Many designers won't know how to use npm, and will wonder how to actually install the plugin. It took me a minute to figure it out, because I was in design mode, and looking for the simple, design friendly solution. I only figured it out when I tried to install it _as a developper_ 
Some designers may not even have node or npm _installed_, they don't always know what a CLI even is, and if they do, they might not know that they have to `cd` into the right folder if they're a CLI novice.

Ideally, the plugin would be included in a runnable form in this repo, or at least there should be clear instructions for how to actually install the plugin, rather than just say "run this in the CLI"

**Comment by JCLaHoot** [comment]
@heytitle do you mind if I contribute to the project README to make it more designer-friend?
Also, would you be opposed to adding the built plugin directly in the repo, or is there a reason that someone should build it themselves?

**Comment by heytitle** [comment]
@JCLaHoot I'm more than welcome to have your PR. 

I'm not sure what you mean by "built" directory.

Is this what you're looking for?
https://github.com/heytitle/latex-sketch-plugin/releases

**Comment by JCLaHoot** [comment]
I mean before updating master, building the updated plugin itself and adding it to the repo. Unless there's a reason why it needs to be built on the computer it's used on?

**Comment by heytitle** [comment]
I've updated `README` adding where to download the plugin. It seems that the PR is not needed. Hence, I'll close it and this issue.

Thanks for the idea and the PR anyway.
