### ISSUE TITLE
insert button obscured

### ISSUE THREAD

**Issue by annabellemoreton** [heytitle/latex-sketch-plugin#4]
The latex starts obscuring the insert button once it goes past a certain length. Is there a way around this?
<img width="760" alt="screen shot 2018-03-30 at 5 00 10 pm" src="https://user-images.githubusercontent.com/37923429/38126573-3b8772a6-343d-11e8-8000-3a9030ef74e1.png">

**Comment by sarfrazb** [comment]
I'm having the same issue :(

I can't press the 'Insert' button as it is **behind** the LaTeX preview box.
I don't know any coding unfortunately, so I'm not sure how to fix this.

@heytitle is there some way to make it so the button is always on top?

Thanks

**Comment by heytitle** [comment]
@annabellemoreton @sarfrazb thanks for opening the issue.  I think I kind of know what is the problem. I will fix it as soon as I have time.

**Comment by heytitle** [comment]
@annabellemoreton @sarfrazb I've fixed the issue.

You can download the new version here: https://github.com/heytitle/latex-sketch-plugin/releases/tag/v5.1.0
