### ISSUE TITLE
I can't find the .Sketchplugin file in any of the versions

### ISSUE THREAD

**Issue by GabrielLeni** [heytitle/latex-sketch-plugin#5]
Thanks for this amazing plugin. I can't seem to be able to install it though.

When I download it I can't find any .sketchplugin files. There's only one file called demo.sketch and doesn't install the plugin. I tried copying some files to the Sketch plugin folder and nothing happens either. I would appreciate your help and please excuse my ignorance if the solution is simple.

Thank you very much!
Gabriel

**Comment by heytitle** [comment]
Sorry for the late reply. 

Can you download it from this URL https://github.com/heytitle/latex-sketch-plugin/releases?
